name: Generate README
on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: List files
      run: |
        echo "Files in repository:"
        ls -la
        echo "Python files:"
        find . -name "*.py" -type f
